# Generated by Django 2.2.10 on 2020-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('runtime', models.DecimalField(decimal_places=2, max_digits=2)),
                ('birth_date', models.DateField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
