# Generated by Django 2.2.10 on 2020-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200309_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='company',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
