# Generated by Django 2.2.10 on 2020-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_movies_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
