# Generated by Django 2.2.10 on 2020-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20200309_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='score',
            field=models.IntegerField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default='SOME STRING'),
        ),
    ]
