# Generated by Django 2.2.10 on 2020-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20200309_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
