# Generated by Django 2.2.10 on 2020-03-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20200309_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='score',
        ),
    ]
