# Generated by Django 2.2.10 on 2020-03-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_remove_movies_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
    ]
