# Generated by Django 2.2.10 on 2020-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20200309_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
