# Generated by Django 2.2.10 on 2020-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_auto_20200309_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.IntegerField(default=''),
        ),
    ]
