# Generated by Django 2.2.10 on 2020-03-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_movies_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
    ]
