# Generated by Django 2.2.10 on 2020-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_remove_movies_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='company',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='name',
        ),
    ]
