# Generated by Django 2.2.10 on 2020-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_auto_20200312_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=1, max_digits=11)),
                ('company', models.CharField(max_length=73)),
                ('country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=9)),
                ('gross', models.DecimalField(decimal_places=1, max_digits=11)),
                ('name', models.CharField(max_length=83)),
                ('rating', models.CharField(max_length=13)),
                ('released', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('star', models.CharField(max_length=27)),
                ('votes', models.IntegerField()),
                ('writer', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'mytable',
                'managed': False,
            },
        ),
    ]
