# Generated by Django 2.2.10 on 2020-03-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_mytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
